version: '3.8'

services:
  backend:
    image: kevram73/payroll:latest
    container_name: payroll
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
