// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payroll.Data;

#nullable disable

namespace Payroll.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20250131161451_FixForeignKeyIssueses")]
    partial class FixForeignKeyIssueses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Payroll.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Payroll.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5c8b9f08-73c7-4644-9781-f83aa803e528",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc31cc3e-fca8-4cf4-abf2-5cef34a4a5ca",
                            Email = "kevram@payroll.com",
                            EmailConfirmed = true,
                            FirstName = "Kevin",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "KEVRAM@PAYROLL.COM",
                            NormalizedUserName = "KEVRAM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM/dpdASiP5rTdq7X5g7MboavGZCQSxD+cWnQ3tbqAnH0yzJLmrUlO2enM2c1JMJxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92ba13ce-b8d3-4a03-bbf6-e1df715d4529",
                            TwoFactorEnabled = false,
                            UserName = "kevram"
                        });
                });

            modelBuilder.Entity("Payroll.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ClockIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ClockOut")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClockIn = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2024, 1, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HoursWorked = 8m,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ClockIn = new DateTime(2024, 1, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2024, 1, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HoursWorked = 8m,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            ClockIn = new DateTime(2024, 1, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2024, 1, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            HoursWorked = 0m,
                            Status = 4
                        });
                });

            modelBuilder.Entity("Payroll.Models.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("BenefitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500.00m,
                            BenefitDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prime de performance annuelle",
                            EmployeeId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200.00m,
                            BenefitDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heures supplémentaires",
                            EmployeeId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 150.00m,
                            BenefitDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indemnité de transport",
                            EmployeeId = 3,
                            Type = 3
                        });
                });

            modelBuilder.Entity("Payroll.Models.Deduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DeductionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Deductions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 300.00m,
                            DeductionDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Impôt sur le revenu",
                            EmployeeId = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.00m,
                            DeductionDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Assurance santé",
                            EmployeeId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 250.00m,
                            DeductionDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cotisation retraite",
                            EmployeeId = 3,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Payroll.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gestion des employés et des ressources humaines.",
                            Name = "Ressources Humaines"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Développement, maintenance et support IT.",
                            Name = "Informatique"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gestion des finances et des budgets.",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Publicité et stratégies de croissance.",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Développement des ventes et gestion des clients.",
                            Name = "Ventes"
                        });
                });

            modelBuilder.Entity("Payroll.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalaryStructureId")
                        .HasColumnType("int");

                    b.Property<int>("TaxInformationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "jean.dupont@example.com",
                            FirstName = "Jean",
                            HireDate = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dupont",
                            PaymentMethodId = 1,
                            Phone = "0612345678",
                            SalaryStructureId = 1,
                            TaxInformationId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "marie.curie@example.com",
                            FirstName = "Marie",
                            HireDate = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Curie",
                            PaymentMethodId = 2,
                            Phone = "0623456789",
                            SalaryStructureId = 2,
                            TaxInformationId = 2
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "albert.einstein@example.com",
                            FirstName = "Albert",
                            HireDate = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Einstein",
                            PaymentMethodId = 3,
                            Phone = "0634567890",
                            SalaryStructureId = 3,
                            TaxInformationId = 3
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Email = "isaac.newton@example.com",
                            FirstName = "Isaac",
                            HireDate = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Newton",
                            PaymentMethodId = 4,
                            Phone = "0645678901",
                            SalaryStructureId = 4,
                            TaxInformationId = 4
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            Email = "ada.lovelace@example.com",
                            FirstName = "Ada",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lovelace",
                            PaymentMethodId = 5,
                            Phone = "0656789012",
                            SalaryStructureId = 5,
                            TaxInformationId = 5
                        });
                });

            modelBuilder.Entity("Payroll.Models.EmployeeProject", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProjects");
                });

            modelBuilder.Entity("Payroll.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1500.00m,
                            DueDate = new DateTime(2025, 2, 15, 16, 14, 50, 752, DateTimeKind.Utc).AddTicks(5830),
                            EmployeeId = 1,
                            InvoiceNumber = "INV-202401",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2000.00m,
                            DueDate = new DateTime(2025, 2, 10, 16, 14, 50, 752, DateTimeKind.Utc).AddTicks(5830),
                            EmployeeId = 2,
                            InvoiceNumber = "INV-202402",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1800.00m,
                            DueDate = new DateTime(2025, 1, 26, 16, 14, 50, 752, DateTimeKind.Utc).AddTicks(5840),
                            EmployeeId = 3,
                            InvoiceNumber = "INV-202403",
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2200.00m,
                            DueDate = new DateTime(2025, 2, 20, 16, 14, 50, 752, DateTimeKind.Utc).AddTicks(5840),
                            EmployeeId = 4,
                            InvoiceNumber = "INV-202404",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Payroll.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1500.00m,
                            EmployeeId = 1,
                            PaymentDate = new DateTime(2025, 1, 24, 16, 14, 50, 752, DateTimeKind.Utc).AddTicks(5880),
                            PaymentMethodId = 1,
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2000.00m,
                            EmployeeId = 2,
                            PaymentDate = new DateTime(2025, 1, 28, 16, 14, 50, 752, DateTimeKind.Utc).AddTicks(5880),
                            PaymentMethodId = 2,
                            Status = "Processed"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1800.50m,
                            EmployeeId = 3,
                            PaymentDate = new DateTime(2025, 1, 31, 16, 14, 50, 752, DateTimeKind.Utc).AddTicks(5880),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Payroll.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "123456789",
                            BankName = "Bank of America",
                            EmployeeId = 1,
                            RoutingNumber = "987654321",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "234567891",
                            BankName = "Chase Bank",
                            EmployeeId = 2,
                            RoutingNumber = "876543219",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "345678912",
                            BankName = "Wells Fargo",
                            EmployeeId = 3,
                            RoutingNumber = "765432198",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "",
                            BankName = "",
                            EmployeeId = 4,
                            RoutingNumber = "",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Payroll.Models.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PayPeriodEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PayPeriodStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Payrolls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            GrossSalary = 3000.00m,
                            NetSalary = 2500.00m,
                            PayPeriodEnd = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayPeriodStart = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalDeductions = 500.00m
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            GrossSalary = 4000.00m,
                            NetSalary = 3300.00m,
                            PayPeriodEnd = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayPeriodStart = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalDeductions = 700.00m
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            GrossSalary = 3500.00m,
                            NetSalary = 2900.00m,
                            PayPeriodEnd = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayPeriodStart = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalDeductions = 600.00m
                        });
                });

            modelBuilder.Entity("Payroll.Models.Profit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Profits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculatedDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalExpenses = 75000.00m,
                            TotalRevenue = 100000.00m
                        },
                        new
                        {
                            Id = 2,
                            CalculatedDate = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalExpenses = 80000.00m,
                            TotalRevenue = 120000.00m
                        },
                        new
                        {
                            Id = 3,
                            CalculatedDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalExpenses = 82000.00m,
                            TotalRevenue = 110000.00m
                        });
                });

            modelBuilder.Entity("Payroll.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 50000.00m,
                            Description = "Enhancing the payroll system for better efficiency and security.",
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Payroll System Upgrade",
                            StartDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 75000.00m,
                            Description = "Adding new benefits for employees, including healthcare and retirement plans.",
                            Name = "Employee Benefits Expansion",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Budget = 60000.00m,
                            Description = "Developing a system to automatically calculate tax deductions.",
                            EndDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Automated Tax Calculation",
                            StartDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Budget = 60000.00m,
                            Description = "Developing a system to automatically calculate tax deductions.",
                            EndDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Automated Tax Calculation Hell",
                            StartDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Payroll.Models.SalaryStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("HousingAllowance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OtherAllowances")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("SalaryStructures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasicSalary = 5000.00m,
                            EffectiveDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HousingAllowance = 1500.00m,
                            MedicalAllowance = 300.00m,
                            OtherAllowances = 200.00m,
                            TransportAllowance = 500.00m
                        },
                        new
                        {
                            Id = 2,
                            BasicSalary = 6000.00m,
                            EffectiveDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HousingAllowance = 1800.00m,
                            MedicalAllowance = 400.00m,
                            OtherAllowances = 250.00m,
                            TransportAllowance = 600.00m
                        },
                        new
                        {
                            Id = 3,
                            BasicSalary = 5500.00m,
                            EffectiveDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            HousingAllowance = 1700.00m,
                            MedicalAllowance = 350.00m,
                            OtherAllowances = 225.00m,
                            TransportAllowance = 550.00m
                        });
                });

            modelBuilder.Entity("Payroll.Models.TaskEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TaskEmployees");
                });

            modelBuilder.Entity("Payroll.Models.TaxInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Exemptions")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("FilingStatus")
                        .HasColumnType("int");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TaxWithholding")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("TaxInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            Exemptions = 1000.00m,
                            FilingStatus = 0,
                            TaxIdentificationNumber = "TIN123456789",
                            TaxWithholding = 500.00m
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            Exemptions = 1500.00m,
                            FilingStatus = 1,
                            TaxIdentificationNumber = "TIN987654321",
                            TaxWithholding = 400.00m
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            Exemptions = 1200.00m,
                            FilingStatus = 3,
                            TaxIdentificationNumber = "TIN456789123",
                            TaxWithholding = 600.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Payroll.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Payroll.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payroll.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Payroll.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Payroll.Models.Attendance", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.Benefit", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithMany("Benefits")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.Deduction", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithMany("Deductions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.Employee", b =>
                {
                    b.HasOne("Payroll.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Payroll.Models.EmployeeProject", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payroll.Models.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Payroll.Models.Invoice", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.Payment", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payroll.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.Navigation("Employee");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Payroll.Models.PaymentMethod", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithOne("PaymentMethod")
                        .HasForeignKey("Payroll.Models.PaymentMethod", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.Payroll", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.SalaryStructure", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithOne("SalaryStructure")
                        .HasForeignKey("Payroll.Models.SalaryStructure", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.TaskEmployee", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.TaxInformation", b =>
                {
                    b.HasOne("Payroll.Models.Employee", "Employee")
                        .WithOne("TaxInformation")
                        .HasForeignKey("Payroll.Models.TaxInformation", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payroll.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Payroll.Models.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Benefits");

                    b.Navigation("Deductions");

                    b.Navigation("EmployeeProjects");

                    b.Navigation("PaymentMethod")
                        .IsRequired();

                    b.Navigation("Payrolls");

                    b.Navigation("SalaryStructure")
                        .IsRequired();

                    b.Navigation("TaxInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("Payroll.Models.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
